config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "reservations/new", to: "reservations#new", as: "new_reservation"
  get "reservations/:id/edit", to: "reservations#edit", as: "edit_reservation"
  resources :reservations

  scope :api, defaults: { format: :json } do
    resources :reservations
  end
end

app/models/reservation.rb
# frozen_string_literal: true

module Types
  include Dry.Types()
end

class Reservation < Dry::Struct
  transform_keys(&:to_sym)

  attribute :id, Types::Params::String.optional.default(nil)
  attribute :hotel_name, Types::Params::String
  attribute :price, Types::Params::Integer
  attribute :currency, Types::Params::String
  attribute :entry_date, Types::Params::DateTime
  attribute :departure_date, Types::Params::DateTime
  attribute :guest_name, Types::Params::String
  attribute :guest_email, Types::Params::String
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  def index
    fetching = reservations_service.list_all

    respond_to do |format|
      if fetching.success?
        format.html { render(locals: { reservations: html_presenter.present(fetching.result) }) }
        format.json { render(json: json_presenter.present(fetching.result), status: :ok) }
      else
        format.html { render(locals: { errors: fetching.errors }) }
        format.json { render(json: { errors: fetching.errors }, status: :unprocessable_entity) }
      end
    end
  end

  def show
    fetching = reservations_service.find_by_id(params[:id])

    respond_to do |format|
      if fetching.success?
        format.html { render(locals: { reservation: html_presenter.present(fetching.result) }) }
        format.json { render(json: json_presenter.present(fetching.result), status: :ok) }
      else
        format.html { render(locals: { errors: fetching.errors }) }
        format.json { render(json: { errors: fetching.errors }, status: :unprocessable_entity) }
      end
    end
  end

  def create
    creating = reservations_service.create(reservation_params)

    respond_to do |format|
      if creating.success?
        format.html { redirect_to(reservation_url(creating.result.id)) }
        format.json { render(json: json_presenter.present(creating.result), status: :ok) }
      else
        flash.now[:alert] = creating.errors
        format.html { render(:new, locals: { params: reservation_params }) }
        format.json { render(json: { errors: creating.errors }, status: :unprocessable_entity) }
      end
    end
  end

  def edit
    finding = reservations_service.find_by_id(params[:id])

    if finding.success?
      render(locals: { reservation: html_presenter.present(finding.result) })
    else
      render(locals: { errors: finding.errors })
    end
  end

  def update
    updating = reservations_service.update(params[:id], reservation_params)

    if updating.success?
      respond_to do |format|
        format.html { redirect_to(reservation_path(params[:id])) }
        format.json { render(json: json_presenter.present(updating.result), status: :ok) }
      end
    else
      respond_to do |format|
        format.html { redirect_to(edit_reservation_path(params[:id]), alert: updating.errors) }
        format.json { render(json: { errors: updating.errors }, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    deleting = reservations_service.delete(params[:id])

    respond_to do |format|
      if deleting.success?
        format.html { redirect_to(reservations_path) }
        format.json { head(:ok) }
      else
        format.html { redirect_to(edit_reservation_path(params[:id]), alert: deleting.errors) }
        format.json { render(json: { errors: deleting.errors }, status: :unprocessable_entity) }
      end
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      :hotel_name,
      :price,
      :currency,
      :entry_date,
      :departure_date,
      :guest_name,
      :guest_email,
    ).to_h
  end

  def reservations_service
    ReservationsService.new
  end

  def json_presenter
    JsonReservationPresenter
  end

  def html_presenter
    HtmlReservationPresenter
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/edit.html.slim
.container
  .reservation-form
    h1 Edit Reservation
    - if flash[:alert].present?
      .alert.alert-danger= flash[:alert]
    = form_with(scope: :reservation, url: reservation_path(reservation.id), method: :put) do |f|
      .card
        .card-body
          .mb-3
            = f.label :hotel_name, class: "form-label font-weight-bold"
            = f.text_field :hotel_name, value: reservation.hotel_name, class: "form-control"
          .mb-3
            = f.label :price, class: "form-label font-weight-bold"
            = f.text_field :price, value: reservation.price, class: "form-control"
          .mb-3
             = f.label :currency, class: "form-label font-weight-bold"
             = f.text_field :currency, value: reservation.currency, class: "form-control"
          .mb-3
            = f.label :entry_date, class: "form-label font-weight-bold"
            = f.date_field :entry_date, value: reservation.entry_date, class: "form-control"
          .mb-3
            = f.label :departure_date, class: "form-label font-weight-bold"
            = f.date_field :departure_date, value: reservation.departure_date, class: "form-control"
          .mb-3
            = f.label :guest_name, class: "form-label font-weight-bold"
            = f.text_field :guest_name, value: reservation.guest_name, class: "form-control"
          .mb-3
            = f.label :guest_email, class: "form-label font-weight-bold"
            = f.email_field :guest_email, value: reservation.guest_email, class: "form-control"

          .actions
            = f.submit 'Save', class: "btn btn-primary"
            = link_to 'Back', reservations_path, class: "btn btn-secondary"

app/views/reservations/index.html.slim
.container
  .page-header
    h1 Reservations

.container
  table.table.table-striped
    thead
      tr
        th Hotel Name
        th Price
        th Currency
        th Entry Date
        th Departure Date
        th Guest Name
        th Guest Email
        th Actions
    tbody
      - reservations.each do |reservation|
        tr
          td = reservation.hotel_name
          td = reservation.price
          td = reservation.currency
          td = reservation.entry_date
          td = reservation.departure_date
          td = reservation.guest_name
          td = reservation.guest_email
          td
            .d-inline
              = link_to 'Show', reservation_path(reservation.id), class: 'btn btn-primary mr-2'
            .d-inline
              = link_to 'Edit', edit_reservation_path(reservation.id), class: 'btn btn-warning mr-2'
            .d-inline-block
              = button_to 'Delete', reservation_path(reservation.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }

  = link_to 'New Reservation', new_reservation_path, class: 'btn btn-success mt-4'

app/views/reservations/new.html.slim
.container
  .reservation-form
    h1 New Reservation
    - if flash[:alert].present?
      .alert.alert-danger= flash[:alert]
    = form_with(scope: :reservation, url: reservations_path) do |f|
      .card
        .card-body
          .mb-3
            = f.label :hotel_name, class: "form-label font-weight-bold"
            = f.text_field :hotel_name, value: params[:hotel_name], class: "form-control"
          .mb-3
            = f.label :price, class: "form-label font-weight-bold"
            = f.text_field :price, value: params[:price], class: "form-control"
          .mb-3
             = f.label :currency, class: "form-label font-weight-bold"
             = f.text_field :currency,value: params[:currency], class: "form-control"
          .mb-3
            = f.label :entry_date, class: "form-label font-weight-bold"
            = f.date_field :entry_date,value: params[:entry_date], class: "form-control"
          .mb-3
            = f.label :departure_date, class: "form-label font-weight-bold"
            = f.date_field :departure_date, value: params[:departure_date],class: "form-control"
          .mb-3
            = f.label :guest_name, class: "form-label font-weight-bold"
            = f.text_field :guest_name,value: params[:guest_name], class: "form-control"
          .mb-3
            = f.label :guest_email, class: "form-label font-weight-bold"
            = f.email_field :guest_email, value: params[:guest_email] ,class: "form-control"

          .actions
            = f.submit 'Save', class: "btn btn-primary"
            = link_to 'Back', reservations_path, class: "btn btn-secondary"

app/views/reservations/show.html.slim
.reservation-form
  h1 Reservation Details
  .card
    .card-body
      dl class="row"
        dt class="col-sm-4" Hotel Name:
        dd class="col-sm-10" = reservation.hotel_name
        dt class="col-sm-4" Price:
        dd class="col-sm-10" = reservation.price
        dt class="col-sm-4" Currency:
        dd class="col-sm-10" = reservation.currency
        dt class="col-sm-4" Entry Date:
        dd class="col-sm-10" = reservation.entry_date
        dt class="col-sm-4" Departure Date:
        dd class="col-sm-10" = reservation.departure_date
        dt class="col-sm-4" Guest Name:
        dd class="col-sm-10" = reservation.guest_name
        dt class="col-sm-4" Guest Email:
        dd class="col-sm-10" = reservation.guest_email

      div class="row"
        div class="col-sm-6"
          = link_to 'Back', reservations_path, class: 'btn btn-secondary'
        div class="col-sm-6 text-right"
          = link_to 'Edit', edit_reservation_path(reservation.id), class: 'btn btn-primary'